#Fake News Classifer with LSTM

1.   List item
2.   List item



In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('train.csv')

In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
###Droping an values
df=df.dropna()

In [ ]:
##Get the independent Features
X=df.drop('label',axis=1)

In [ ]:
##Get the Dependent feature
y=df['label']

In [ ]:
X.shape

(18285, 4)

In [ ]:
y.shape

(18285,)

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.15.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
### Vocabulary size
voc_size=5000

# Onehot Representation

In [ ]:
message=X.copy()

In [ ]:
message.reset_index(inplace=True)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

### Dataset preprocessing

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus=[]
for i in range(0,len(message)):
  print(i)
  review = re.sub('[^a-zA-Z]', ' ',message['title'][i])
  review = review.lower()
  review =review.split()

  review =[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)


Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [ ]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[2875, 1860, 3638, 3130, 4123, 540, 4472, 1076, 4640, 1849],
 [350, 2781, 54, 889, 3280, 1206, 375],
 [2450, 2932, 2461, 1917],
 [2270, 1145, 4600, 3739, 2294, 2891],
 [1947, 3280, 1655, 2634, 3548, 3117, 3280, 704, 2786, 3183],
 [4456,
  588,
  1612,
  4561,
  3988,
  4730,
  3364,
  2604,
  4622,
  995,
  2401,
  603,
  4444,
  2551,
  375],
 [1591, 4116, 2418, 4089, 3552, 1578, 1107, 4796, 3891, 3286, 640],
 [1060, 1885, 4659, 3958, 2258, 2989, 4730, 2582, 3891, 3286, 640],
 [4735, 1855, 2112, 1522, 3245, 3352, 162, 374, 4730, 1440],
 [1821, 1351, 2619, 3728, 4300, 1534, 2603, 475],
 [1268, 559, 3789, 2774, 1312, 123, 3853, 4170, 4277, 1785, 2519],
 [3739, 2893, 4123, 3352, 4730, 2258],
 [557, 3811, 2886, 3748, 2426, 150, 2612, 1618, 2019],
 [1821, 3408, 633, 3248, 2027, 4431, 3294, 3891, 3286, 640],
 [2335, 2795, 1743, 1633, 4963, 3891, 3286, 640],
 [2148, 767, 1696, 2532, 4208, 1889, 2558, 4819, 3946, 2346],
 [1630, 4061, 2781],
 [119, 3658, 1830, 4959, 4730, 596, 816, 375],
 [39

## Embedding Representation

In [ ]:

sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 1076 4640 1849]
 [   0    0    0 ... 3280 1206  375]
 [   0    0    0 ... 2932 2461 1917]
 ...
 [   0    0    0 ... 3891 3286  640]
 [   0    0    0 ...  416 4075 2823]
 [   0    0    0 ...  965 3268 1765]]


In [ ]:
len(embedded_docs)

18285

### Creating Model

In [ ]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_14 (Embedding)    (None, 20, 40)            200000    
                                                                 
 lstm_14 (LSTM)              (None, 100)               56400     
                                                                 
 dense_14 (Dense)            (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
len(embedded_docs),y.shape

(18285, (18285,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X_final,y_final,test_size=0.33,random_state=42)

##Model Training

In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 14s 49ms/step - loss: 0.3322 - accuracy: 0.8433 - val_loss: 0.2138 - val_accuracy: 0.9143
Epoch 2/10
192/192 [==============================] - 10s 55ms/step - loss: 0.1387 - accuracy: 0.9460 - val_loss: 0.1997 - val_accuracy: 0.9208
Epoch 3/10
192/192 [==============================] - 10s 53ms/step - loss: 0.0965 - accuracy: 0.9639 - val_loss: 0.2623 - val_accuracy: 0.9160
Epoch 4/10
192/192 [==============================] - 10s 49ms/step - loss: 0.0687 - accuracy: 0.9756 - val_loss: 0.2263 - val_accuracy: 0.9163
Epoch 5/10
192/192 [==============================] - 10s 51ms/step - loss: 0.0424 - accuracy: 0.9861 - val_loss: 0.3259 - val_accuracy: 0.9162
Epoch 6/10
192/192 [==============================] - 8s 41ms/step - loss: 0.0293 - accuracy: 0.9900 - val_loss: 0.2706 - val_accuracy: 0.9133
Epoch 7/10
192/192 [==============================] - 10s 50ms/step - loss: 0.0170 - accuracy: 0.9950 - val_loss: 0.3989 - val_accuracy: 

## Adding Dropout

In [ ]:
from tensorflow.keras.layers import Dropout

# Creatin Model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
!pip install tensorflow


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam

In [ ]:
model_type = type(model).__name__
print(f"Model type: {model_type}")

Model type: Sequential


In [ ]:
if model_type == "Sequential":
    y_pred = model.predict(X_test)

189/189 [==============================] - 2s 9ms/step


### Performance Metrix

In [ ]:
y_pred= model.predict(X_test)

189/189 [==============================] - 2s 11ms/step


In [ ]:
!pip install --upgrade pip


In [ ]:
pip install scikit-learn

In [ ]:
print(type(y_test))
print(type(y_pred))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
if type(y_test) == np.ndarray and type(y_pred) == np.ndarray:
    # Convert y_test to a 1D array
    y_test = y_test.ravel()
    # Convert y_pred to a 1D array
    y_pred = y_pred.ravel()

In [ ]:
y_pred = [0 if p < 0.5 else 1 for p in y_pred]

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix=confusion_matrix(y_test, y_pred)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5403479701739851